# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="transcribe"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Package for audio transcriptions"

HOMEPAGE="http://elpa.gnu.org/packages/transcribe.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
