# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="transient-cycles"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Define command variants with transient cycling"

HOMEPAGE="https://git.spwhitton.name/dotfiles/tree/.emacs.d/site-lisp/transient-cycles.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
