# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="lv"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Other echo area"

HOMEPAGE="https://elpa.gnu.org/packages/lv.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
