# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="wisi"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Utilities for implementing an indentation/navigation engine using a generalized LR parser"

HOMEPAGE="https://stephe-leake.org/ada/wisitoken.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/seq"
RDEPEND="app-emacs/seq"
