# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="undo-tree"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Treat undo history as a tree"

HOMEPAGE="https://www.dr-qubit.org/undo-tree.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/queue"
RDEPEND="app-emacs/queue"
