# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="PUTINTSEV"
DIST_VERSION="0.011"

inherit perl-module

DESCRIPTION="Validator for JSON Schema Draft4/Draft6/Draft7 and OpenAPI Specification 3.0"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/URI-5.100.0
	dev-lang/perl"
