# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="adjust-parens"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Indent and dedent Lisp code, automatically adjust close parens"

HOMEPAGE="http://elpa.gnu.org/packages/adjust-parens.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
