# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="caps-lock"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Caps-lock as a minor mode"

HOMEPAGE="http://elpa.gnu.org/packages/caps-lock.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
