# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="project"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Operations on the current project"

HOMEPAGE="https://elpa.gnu.org/packages/project.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/xref"
RDEPEND="app-emacs/xref"
