# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="delight"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A dimmer switch for your lighter text"

HOMEPAGE="https://savannah.nongnu.org/projects/delight"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/nadvice"
RDEPEND="app-emacs/nadvice"
