# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="tree-inspector"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Inspector tool for Emacs Lisp object that uses a treeview"

HOMEPAGE="https://github.com/mmontone/emacs-inspector"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/treeview"
RDEPEND="app-emacs/treeview"
