# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ack"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="interface to ack-like tools"

HOMEPAGE="https://github.com/leoliu/ack-el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
