# This is a basic workflow to help you get started with Actions

name: samba

# 控制工作流程运行时间
on:
  schedule:
    # *是yaml中的特殊字符，所以你必须引用这个字符串
    - cron:  '55 11 * * *'


  # 允许您在“操作”选项卡中手动运行此工作流程
  workflow_dispatch:
permissions: write-all
# 工作流程运行由一个或多个可以顺序运行或并行运行的作业组成
jobs:
  # 此工作流包含一个名为“update”的单个作业
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: 克隆存储库
        run: git clone https://github.com/gentoo/gentoo.git
      - name: 转移samba的ebuild
        run: |
          rm -f ./net-fs/samba/*.ebuild
          cp -r gentoo/net-fs/samba/* ./net-fs/samba/
      - name: 更改内容以适配llvm-libunwind并删除克隆的存储库
        run: |
          sed -i 's/libunwind/llvm-libunwind/g' ./net-fs/samba/samba-*
          rm -rf gentoo
      - name: 推送
        run: |
          git config --global user.email "qwe7951384261@outlook.com"
          git config --global user.name "fyn5908"
          git add .
          git commit -m "update samba [automatic commit]"
          git push
