# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="gnu-elpa-keyring-update"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Update Emacs's GPG keyring for GNU ELPA"

HOMEPAGE="https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
