# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="yasnippet-classic-snippets"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="\"Classic\" yasnippet snippets"

HOMEPAGE="http://elpa.gnu.org/packages/yasnippet-classic-snippets.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/yasnippet"
RDEPEND="app-emacs/yasnippet"
