# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="satchel"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A bag for your files, separated by git branches"

HOMEPAGE="https://elpa.gnu.org/packages/satchel.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/project"
RDEPEND="app-emacs/project"
