# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="sweeprolog"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Embedded SWI-Prolog"

HOMEPAGE="https://git.sr.ht/~eshel/sweep"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
