# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="KAZEBURO"
DIST_VERSION="0.05"

inherit perl-module

DESCRIPTION="Plack::Builder extension"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Plack-1.4.800
	dev-perl/Module-Build
	dev-perl/List-MoreUtils
	dev-perl/Net-CIDR-Lite
	dev-lang/perl"
