# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="debbugs"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="SOAP library to access debbugs servers"

HOMEPAGE="https://elpa.gnu.org/packages/debbugs.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/soap-client"
RDEPEND="app-emacs/soap-client"
