# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="compact-docstrings"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Shrink blank lines in docstrings and doc comments"

HOMEPAGE="https://github.com/cpitclaudel/compact-docstrings"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
