# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="emacs-gc-stats"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Collect Emacs GC statistics"

HOMEPAGE="https://git.sr.ht/~yantar92/emacs-gc-stats"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
