# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="soap-client"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Access SOAP web services"

HOMEPAGE="https://github.com/alex-hhh/emacs-soap-client"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
