# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="TOKUHIROM"
DIST_VERSION="1.11"

inherit perl-module

DESCRIPTION="Extremely fast HTML escaping"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Module-Build-Pluggable-PPPort-0.04
	dev-perl/Module-Build
	dev-perl/Test-Requires
	dev-lang/perl"
