# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="smart-yank"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A different approach of yank pointer handling"

HOMEPAGE="http://elpa.gnu.org/packages/smart-yank.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
