# Copyright 2016-2023 Bryan Gardiner <bog@khumba.net>
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.6.7

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Qt bindings for Haskell - C++ library"
HOMEPAGE="https://khumba.net/projects/qtah"

LICENSE="LGPL-3+"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/qtah-generator-0.8:=[profile?] <dev-haskell/qtah-generator-0.9:=[profile?]
	>=dev-lang/ghc-7.8.2:=
	dev-qt/qtcore:5
	dev-qt/qtgui:5
	dev-qt/qtwidgets:5
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0
"

GHC_BOOTSTRAP_PACKAGES=(qtah-generator)
