# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="TOMMY"
DIST_VERSION="4.201720"

inherit perl-module

DESCRIPTION="Easy, versatile, portable file handling"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Unicode-UTF8-0.620.0
	dev-perl/Module-Build
	dev-perl/Test-NoWarnings
	dev-lang/perl"
