# Copyright 2016-2023 Bryan Gardiner <bog@khumba.net>
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
# Needed because haskell-cabal.eclass uses ${S} too early:
CABAL_FILE="${WORKDIR}/${P}/${PN}/${PN}.cabal"

inherit git-r3 haskell-cabal

DESCRIPTION="Generator for Qtah Qt bindings"
HOMEPAGE="https://khumba.net/projects/qtah"
EGIT_REPO_URI="https://gitlab.com/khumba/qtah.git"
S="${WORKDIR}/${P}/${PN}"

LICENSE="LGPL-3+"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND=">=dev-haskell/haskell-src-1.0:=[profile?] <dev-haskell/haskell-src-1.1:=[profile?]
	>=dev-haskell/hoppy-generator-0.8.1:=[profile?]
	>=dev-haskell/hoppy-std-0.8:=[profile?]
	>=dev-haskell/mtl-2.2.1:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-lang/ghc-8.2.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0
"
