# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="vc-got"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="VC backend for Game of Trees VCS"

HOMEPAGE="https://projects.omarpolo.com/vc-got.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
