# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="cl-generic"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Forward cl-generic compatibility for Emacs<25"

HOMEPAGE="http://elpa.gnu.org/packages/cl-generic.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
