Index: work/sogo-connector-sogo-connector-68.0.1/Makefile
===================================================================
--- work.orig/sogo-connector-sogo-connector-68.0.1/Makefile
+++ work/sogo-connector-sogo-connector-68.0.1/Makefile
@@ -1,5 +1,4 @@
 PACKAGE = sogo-connector
-GIT_REV = $(shell git rev-parse --verify HEAD | cut -c1-10)
 
 ifeq ($(shell uname),Darwin)
 VERSION = $(shell grep em:version install.rdf | sed -E 's@(em:version=|"| )@@g')
@@ -8,7 +7,7 @@ VERSION = $(shell grep em:version instal
 endif
 
 FIND_FILTER = ! -path './custom/*' -type f
-XPI_ARCHIVE = $(PACKAGE)-$(VERSION)-$(GIT_REV).xpi
+XPI_ARCHIVE = $(PACKAGE)-$(VERSION).xpi
 
 SHELL=bash
 ZIP=zip
