# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="validate"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Schema validation for Emacs-lisp"

HOMEPAGE="http://elpa.gnu.org/packages/validate.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/seq"
RDEPEND="app-emacs/seq"
