# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="JMCNAMARA"
DIST_VERSION="1.09"

inherit perl-module

DESCRIPTION="Create a new file in the Excel 2007+ XLSX format."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Archive-Zip-1.680.0
	dev-lang/perl"
