# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="YANICK"
DIST_VERSION="1.1.17"

inherit perl-module

DESCRIPTION="Class for easy date and time manipulation"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/TimeDate
	dev-perl/Test-Warnings
	dev-lang/perl"
