# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="auto-correct"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Remembers and automatically fixes past corrections"

HOMEPAGE="http://elpa.gnu.org/packages/auto-correct.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
