# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="altcaps"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Apply alternating letter casing to convey sarcasm or mockery"

HOMEPAGE="https://git.sr.ht/~protesilaos/altcaps"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
