# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="python"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Python's flying circus support for Emacs"

HOMEPAGE="https://github.com/fgallina/python.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
