# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="RJBS"
DIST_VERSION="1.709"

inherit perl-module

DESCRIPTION="test routines for testing numbers against tolerances"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Sub-Exporter-0.988.0
	dev-lang/perl"
