# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="luwak"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Web browser based on lynx -dump."

HOMEPAGE="https://g.ypei.me/luwak.git"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
