# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="JBERGER"
DIST_VERSION="1.02"

inherit perl-module

DESCRIPTION="Monkey patching with test mocking in mind"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Module-Build-Tiny-0.39.0
	dev-perl/Module-Build
	dev-lang/perl"
