# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="RJBS"
DIST_VERSION="0.018"

inherit perl-module

DESCRIPTION="A more casual approach to creating and sending Email:: emails"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=">=dev-perl/Params-Util-1.102.0
	dev-perl/Email-MIME
	>=dev-perl/Email-Sender-1.300.35
	dev-perl/Test-Fatal
	dev-perl/Module-Runtime
	dev-perl/Moo
	dev-lang/perl"
