# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="url-http-ntlm"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="NTLM authentication for the url library"

HOMEPAGE="https://code.google.com/p/url-http-ntlm/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/ntlm"
RDEPEND="app-emacs/ntlm"
