#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/vpnserver"
command_args="start"
description="SoftEther VPN Server"
name="SoftEther VPN Server"
start_stop_daemon_args="-q"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	need net
}

start_post() {
	pgrep -n "$procname" > "$pidfile"
}

stop() {
	ebegin "Stopping $name"
	start-stop-daemon --stop --quiet --pidfile "$pidfile" -- stop
	eend $?
}
