# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="boxy-headings"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="View org files in a boxy diagram"

HOMEPAGE="https://gitlab.com/tygrdev/boxy-headings"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/boxy
	app-emacs/org-mode"
RDEPEND="app-emacs/boxy
	app-emacs/org-mode"
