# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="capf-autosuggest"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="History autosuggestions for comint and eshell"

HOMEPAGE="https://repo.or.cz/emacs-capf-autosuggest.git"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
