# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="muse"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Authoring and publishing tool for Emacs"

HOMEPAGE="http://mwolson.org/projects/EmacsMuse.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
