# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="corfu-terminal"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Corfu popup on terminal"

HOMEPAGE="https://codeberg.org/akib/emacs-corfu-terminal"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/corfu
	app-emacs/popon"
RDEPEND="app-emacs/corfu
	app-emacs/popon"
