# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="cl-lib"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Forward cl-lib compatibility library for Emacs<24.3"

HOMEPAGE="https://elpa.gnu.org/packages/cl-lib.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
