# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="JONASBN"
DIST_VERSION="1.61"

inherit perl-module

DESCRIPTION="Data blackboard for Workflows, Actions, Conditions and Validators"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/DateTime-Format-Strptime-1.790.0
	>=dev-perl/Class-Accessor-0.510.0
	>=dev-perl/XML-Simple-2.250.0
	dev-perl/Readonly
	>=dev-perl/DBD-Mock-1.59
	dev-perl/Mock-MonkeyPatch
	dev-perl/File-Slurp
	>=dev-perl/Test-Pod-1.510.0
	dev-perl/Test-Exception
	>=dev-perl/Class-Factory-1.06
	dev-perl/Data-UUID
	dev-perl/Pod-Coverage-TrustPod
	>=dev-perl/Test-Kwalitee-1.280.0
	dev-perl/List-MoreUtils
	dev-perl/DBI
	>=dev-perl/Log-Log4perl-1.540.0
	>=dev-perl/Test-Pod-Coverage-1.100.0
	>=dev-perl/Exception-Class-1.450.0
	dev-perl/SPOPS
	>=dev-perl/DateTime-1.540.0
	dev-lang/perl"
