# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="popon"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="\"Pop\" floating text \"on\" a window"

HOMEPAGE="https://codeberg.org/akib/emacs-popon"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
