# Copyright 2016-2023 Bryan Gardiner <bog@khumba.net>
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
# Needed because haskell-cabal.eclass uses ${S} too early:
CABAL_FILE="${WORKDIR}/${P}/${PN#hoppy-}/${PN}.cabal"

inherit git-r3 haskell-cabal

DESCRIPTION="C++ FFI generator - Code generator"
HOMEPAGE="https://khumba.net/projects/hoppy"
EGIT_REPO_URI="https://gitlab.com/khumba/hoppy.git"
S="${WORKDIR}/${P}/generator"

LICENSE="AGPL-3+"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND=">=dev-haskell/haskell-src-1.0:=[profile?] <dev-haskell/haskell-src-1.1:=[profile?]
	>=dev-haskell/mtl-2.2.1:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/temporary-1.2:=[profile?] <dev-haskell/temporary-1.4:=[profile?]
	>=dev-haskell/text-1.1:=[profile?] <dev-haskell/text-2.1:=[profile?]
	>=dev-lang/ghc-8.2.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24
"
